# Generated by Django 5.2.3 on 2025-06-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_divorcedprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorcedprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
