# Generated by Django 5.2.3 on 2025-06-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_myuser_address_myuser_city_myuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoysProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='boys_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='DisabledProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('disability_type', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='disabled_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='DivorcedProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('reason', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='divorced_profiles/')),
            ],
        ),
        migrations.CreateModel(
            name='GirlsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='girls_profiles/')),
            ],
        ),
    ]
