# Generated by Django 5.2.3 on 2025-06-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_myuser_profile_image_myuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
    ]
