# Generated by Django 5.2.3 on 2025-06-28 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_boysprofile_about_boysprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boysprofile',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_boys', to='myapp.myuser'),
        ),
        migrations.AddField(
            model_name='disabledprofile',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disabled', to='myapp.myuser'),
        ),
        migrations.AddField(
            model_name='divorcedprofile',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_divorced', to='myapp.myuser'),
        ),
        migrations.AddField(
            model_name='girlsprofile',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_girls', to='myapp.myuser'),
        ),
    ]
