# Generated by Django 5.2.3 on 2025-06-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_boysprofile_assigned_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boysprofile',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='disabledprofile',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='divorcedprofile',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='girlsprofile',
            name='assigned_user',
        ),
    ]
