# Generated by Django 5.2.3 on 2025-06-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_boysprofile_assigned_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlsprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
