# Generated by Django 5.2.3 on 2025-06-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_myuser_address_myuser_is_active_myuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_active',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
