# Generated by Django 5.2.3 on 2025-06-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_girlsprofile_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='boysprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disabledprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='divorcedprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
