# Generated by Django 5.2.3 on 2025-06-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_myuser_is_blocked_remove_myuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
