# Generated by Django 5.2.3 on 2025-06-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_boysprofile_is_approved_disabledprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepermission',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilepermission',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
