# Generated by Django 5.2.3 on 2025-06-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_myuser_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='girlsprofile',
            name='caste',
            field=models.CharField(default='', max_length=100),
        ),
    ]
