# Generated by Django 5.2.3 on 2025-06-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_girlsprofile_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
