# Generated by Django 5.2.3 on 2025-06-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profilepermission_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepermission',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='profilepermission',
            name='is_hidden',
        ),
        migrations.DeleteModel(
            name='AssignedProfile',
        ),
    ]
