# Generated by Django 5.2.3 on 2025-06-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_myuser_caste'),
    ]

    operations = [
        migrations.AddField(
            model_name='boysprofile',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='disabledprofile',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='divorcedprofile',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='girlsprofile',
            name='caste',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
