# Generated by Django 5.2.3 on 2025-06-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_boysprofile_caste_disabledprofile_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boysprofile',
            name='caste',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='disabledprofile',
            name='caste',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='divorcedprofile',
            name='caste',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='girlsprofile',
            name='caste',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
