# Generated by Django 5.2.3 on 2025-07-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='RegistrationNotification',
        ),
    ]
