# Generated by Django 5.2.3 on 2025-06-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_boysprofile_caste_alter_disabledprofile_caste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GirlProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='more_photos/')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.girlsprofile')),
            ],
        ),
    ]
