# Generated by Django 5.2.3 on 2025-06-22 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_girlprofilephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoyProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='more_photos/')),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.boysprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DisabledProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='more_photos/')),
                ('disabled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.disabledprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DivorcedProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='more_photos/')),
                ('divorced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='myapp.divorcedprofile')),
            ],
        ),
    ]
