# Generated by Django 5.2.3 on 2025-06-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_boyprofilephoto_disabledprofilephoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boysprofile',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disabledprofile',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='divorcedprofile',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='girlsprofile',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
