# Generated by Django 5.2.3 on 2025-06-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_boysprofile_phone_alter_disabledprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='category',
            field=models.CharField(blank=True, choices=[('girls', 'Girls'), ('boys', 'Boys'), ('disabled', 'Disabled'), ('divorced', 'Divorced')], max_length=20, null=True),
        ),
    ]
