# Generated by Django 5.2.3 on 2025-06-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_myuser_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('disabled', 'Disabled'), ('divorced', 'Divorced')], max_length=20)),
                ('profile_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.myuser')),
            ],
        ),
    ]
